### ISSUE TITLE
Smart picker not working in iOS

### ISSUE THREAD

**Issue by lpbaiser** [ThePaulMcBride/react-native-smart-picker#1]
I'm using react-native-smart-picker in iOS like exemplified in [README.md](https://github.com/ThePaulMcBride/react-native-smart-picker/blob/master/README.md), but not working for me. Please watch the record about picker. The picker did not select any value and always come back to the first option.

Record Screen: [video](https://youtu.be/-GjTXrpcHEk)

**Comment by ThePaulMcBride** [comment]
Sorry @lpbaiser I have only just seen this issue. Did you get it sorted? If not, let me know.

**Comment by lpbaiser** [comment]
@ThePaulMcBride I could not sort. Had to use another component.

**Comment by ThePaulMcBride** [comment]
Sorry man. The issue is with the readme. The `onValueChange` should update the value passed into `selectedValue`. I'll update it soon.
