### ISSUE TITLE
Readme needs updated

### ISSUE THREAD

**Issue by ThePaulMcBride** [ThePaulMcBride/react-native-smart-picker#2]
The example code in the readme doesn't work. It should be updated to show a working example.

**Comment by GavinThomas1192** [comment]
Submitted PR to fix readme example

**Comment by GavinThomas1192** [comment]
Also if you're interested here is my working version with dynamic lists of data to be used with the picker. 
https://github.com/GavinThomas1192/motoMechanicMeeKanic/blob/master/App/Components/vehicleYearPicker.js

**Comment by ThePaulMcBride** [comment]
closed by #6
