### ISSUE TITLE
`label` prop doesn't accept an object type.

### ISSUE THREAD

**Issue by fxalvarezd** [ThePaulMcBride/react-native-smart-picker#4]
Hello,
We are using your component in our project, but need to style the label to match our design.
We did the following:
```
label={isIOS && selectedOption ? <Text style={styles.iosLabel}>{selectedOption.label}</Text> : ''}
```
but it requires to extend the propType validation to:
```
label: PropTypes.oneOfType([PropTypes.string, PropTypes.object]),
```
to avoid a console error.

Same thing needs to be done for `readt-native-togglebox`.

Thanks!

**Comment by ThePaulMcBride** [comment]
Makes sense to me! Would you like to submit a pull request?

**Comment by fxalvarezd** [comment]
Sure thing! I wasn't able to push my local branch remotely, probably need to enable some settings in your repos?

**Comment by ThePaulMcBride** [comment]
If you create a separate for of the repo, make the changes, commit them, then submit a pull request, it should work fine. I can help you with this if you like?

**Comment by fxalvarezd** [comment]
I just posted both PRs, thx!

**Comment by fxalvarezd** [comment]
Hey, was just wondering if you had some time to review the PRs? Thx!

**Comment by ThePaulMcBride** [comment]
Closed by #5

**Comment by fxalvarezd** [comment]
Thank you!

**Comment by fxalvarezd** [comment]
I think you need to update the `react-native-togglebox` dependency to `1.0.3`?
https://github.com/ThePaulMcBride/react-native-smart-picker/blob/master/package.json#L22

**Comment by ThePaulMcBride** [comment]
👍 I'll do this now. I'm an idiot!

**Comment by fxalvarezd** [comment]
😉  Thanks!
